# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 7.x
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Orleans.sln'
    feedsToUse: 'select'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  displayName: '.net restore'
  inputs:
    command: 'restore'
    projects: 'Orleans.sln'
    feedsToUse: 'select'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  displayName: '.net build'
  inputs:
    command: 'build'
    projects: 'Orleans.sln'
    configuration: 'Release'
- task: PublishBuildArtifacts@1
  displayName: 'buils artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/src/Orleans.Client/bin/Debug/net7.0'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@1
  displayName: 'download artifact'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'